LecRazorJavaScript/Models/ErrorViewModel.cs
namespace LecRazorJavaScript.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LecRazorJavaScript/Models/ViewModels/PersonVM.cs
using System.ComponentModel.DataAnnotations;

namespace LecRazorJavaScript.Models.ViewModels;

public class PersonVM
{
    [Required(ErrorMessage = "The name cannot be blank.")]
    public string? Name { get; set; }

    [StringLength(20, MinimumLength = 3, ErrorMessage = "Must be at least 3 and at most 20 characters!")]
    public string? Occupation { get; set; }

    [Range(18, 100)]
    public int Age { get; set; }

    [RegularExpression(@"((\(\d{3}\) ?)|(\d{3}-))?\d{3}-\d{4}", ErrorMessage = "Invalid Phone Number!")]
    public string? Phone { get; set; }

    [Display(Name = "Date of Birth")]
    [DataType(DataType.Date)]
    public DateTime DateOfBirth { get; set; }

    [DataType(DataType.Currency)]
    public decimal PayPerHour { get; set; }

    [EmailAddress(ErrorMessage = "Invalid Email")]
    public string? Email { get; set; }
}

LecRazorJavaScript/Controllers/HomeController.cs
using LecRazorJavaScript.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LecRazorJavaScript.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewData["SomeValue1"] = "From the controller 1";
            ViewBag.SomeValue2 = "From the controller 2";
            return View();
        }

        public IActionResult PersonVMDemo()
        {
            return View();
        }

        public IActionResult JavaScript1()
        {
            return View();
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LecRazorJavaScript/ViewComponents/TimeViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace LecRazorJavaScript.ViewComponents
{
    public class TimeViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var time = DateTime.Now;
            return View(time);
        }
    }
}

LecRazorJavaScript/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Razor Lecture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Lecture Razor</h1>
<!-- This is a client-side comment -->
@* This is a server-side comment *@
Some text
@* 
    This is another server-side comment
*@
@{
   string greet = "hello";
   char gender = 'M';
   double val = 12.3;

   val = val * 100;
}
<p>@greet @gender @val</p>
<p>@greet Jeff.  You are @gender. Value is @val.</p>

@if (gender == 'M')
{
   <h3>Male</h3>
}
else
{
   <h3>Female</h3>
}

@for(int i = 2; i <= 20; i+=2)
{
   <span>@i</span>
}

@{
   string[] names = {"Jeff", "Evelyn", "Darien", "Dana", "Dylan"};
}
<h1>A section</h1>
@section MySection{
    <h2>This is a section</h2>
}
<ul>
@foreach (var n in names)
{
   <li>@n</li>
}
</ul>
@{
   var foo = true;
   var bar = "some value";
}
@if (foo)
{
    <text>Plain Text </text>
}
<br />
@if (foo)
{
   @:Plain Text and @bar
}
<br />
345 * 67 % 34 = @(345 * 67 % 34)
<br />
@@ was escaped
<partial name="_MyPartialView" />
@await Html.PartialAsync("_MyPartialView")
<p>@ViewData["SomeValue1"]</p>
<p>@ViewBag.SomeValue1</p>
<p>@ViewData["SomeValue2"]</p>
<p>@ViewBag.SomeValue2</p>
@await  Component.InvokeAsync("Time")

LecRazorJavaScript/Views/Home/JavaScript1.cshtml
@{
    ViewData["Title"] = "JavaScript 1";
}

<h1>@ViewData["Title"]</h1>

@section Scripts{
    <script defer src="~/js/myjs.js"></script>
}

LecRazorJavaScript/Views/Home/PersonVMDemo.cshtml
@model LecRazorJavaScript.Models.ViewModels.PersonVM

@{
    ViewData["Title"] = "PersonVMDemo";
}

<h1>PersonVMDemo</h1>

<h4>PersonVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PersonVMDemo">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Occupation" class="control-label"></label>
                <input asp-for="Occupation" class="form-control" />
                <span asp-validation-for="Occupation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PayPerHour" class="control-label"></label>
                <input asp-for="PayPerHour" class="form-control" />
                <span asp-validation-for="PayPerHour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LecRazorJavaScript/Views/Home/_MyPartialView.cshtml
<h1>My Partial View</h1>

LecRazorJavaScript/Views/Shared/Components/Time/Default.cshtml
@model DateTime

<p>
   The time is @Model.ToString("HH:mm tt on MMM dd yyyy")
</p>

LecRazorJavaScript/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LecRazorJavaScript.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lecture Razor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            @await RenderSectionAsync("MySection", required: false)
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LecRazorJavaScript - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>